### ISSUE TITLE
Include LICENSE in pypi source package

### ISSUE THREAD

**Issue by jenzopr** [brentp/interlap#5]
Hi Brent!

I wondered if it is possible to include the `LICENSE` file in the source package that is available on Pypi.  Background is that I wanted to add `interlap` to [conda-forge](https://conda-forge.org) in order to reference it easily in conda envs. Unfortunately, the recipe fails during linting, because of the license file.

As far as I see it, adding a 
```
data_files = [("", ["LICENSE"])]
```
to the `setup()` call in `setup.py` should do the trick. 
Please let me know what you think.

Thanks,
Jens

**Comment by brentp** [comment]
yes. would you mind opening a PR for this?
